version: "3"
services:
  redis:
    image: redis/redis-stack:6.2.4-v4
    container_name: roc-redis
    ports:
      - "6379:6379"
  minio:
    image: minio/minio
    command: server /data --console-address ":9001"
    container_name: roc-minio
    hostname: roc-minio
    environment:
      MINIO_ROOT_USER: "roc"
      MINIO_ROOT_PASSWORD: "roc-minio-pwd"
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - data:/data
  app:
    init: true
    entrypoint:
    - sleep
    - infinity
    build:
      context: .
      dockerfile: Dockerfile
    user: node
    ports:
        - 3000:3000
        - 5000:5000
    volumes:
    - type: bind
      source: /var/run/docker.sock
      target: /var/run/docker.sock
    depends_on:
        - redis
        - minio
volumes:
  data:
