platform:
  image:
    registry: yceiotc.azurecr.io
    repository: roc/roc-platform
    tag: k8s.1
  replica:
    replicaCount: 1
  api-key: None
  s3:
    user: roc
    pwd: roc-minio-pwd

tunnel:
  image:
    registry: yceiotc.azurecr.io
    repository: roc/roc-tunnel
    tag: k8s.1

minio:
  defaultBuckets: roc
  auth:
    rootUser: roc
    rootPassword: roc-minio-pwd

redis:
  image:
    registry: docker.io
    repository: redis/redis-stack-server
    tag: 6.2.6-v4
    pullPolicy: Always
  replica:
    replicaCount: 1
  auth:
    enabled: false
