name: ci

on:
  push:
    paths-ignore:
      - "**.md"
      - "**.go"
  pull_request:
    paths-ignore:
      - "**.md"
      - "**.go"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm install -g lerna
      - run: lerna add @roc/core --scope=@roc/platform
      - run: lerna add @roc/core --scope=@roc/tunnel
      - run: lerna bootstrap
      - run: lerna run build
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm install -g lerna
      - run: npm install -ws
      - run: lerna add @roc/core --scope=@roc/platform
      - run: lerna add @roc/core --scope=@roc/tunnel
      - run: lerna bootstrap
      - run: lerna run lint
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Prepare Packages
        run: |
          npm install -g lerna
          npm install -ws
          lerna add @roc/core --scope=@roc/platform
          lerna add @roc/core --scope=@roc/tunnel
          lerna bootstrap
          lerna run build
        
      - name: Deploy Services for Test
        run: docker-compose -f services.yaml up -d && sleep 1
      - name: Test All Packages
        run: lerna run test
        env:
          REDIS_URL: redis://localhost:6379
          S3_HOST: minio
          S3_PORT: 9000
          S3_ACCESS_KEY: roc
          S3_SECRET_KEY: roc-minio-pwd
      - name: Collect Coverage Reports
        run: |
          sudo apt-get install lcov -y
          mkdir -p coverage
          find ./packages -name lcov.info -exec echo -a {} \; | xargs lcov -o coverage/lcov.info
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
