name: docker-publish
on:
  create:
    tags:
      - v*
jobs:
  roc-platform:
    runs-on: ubuntu-latest
    env:
      DOCKER_REGISTRY: ghcr.io
      DOCKER_REPOSITORY: yusufcanb/roc
      DOCKER_IMAGE: roc-platform

    steps:
    - name: checkout
      uses: actions/checkout@v2

    - name: publish roc-platform
      uses: docker/build-push-action@v2
      with:
        push: true
        context: .
        dockerfile: Dockerfile.platform
        tags: ${DOCKER_REGISTRY}/${DOCKER_REPOSITORY}/${DOCKER_IMAGE}:${{ env.TAG_NAME }}

    - name: publish
      uses: docker/push-action@v1
      with:
        tags: ${DOCKER_REGISTRY}/${DOCKER_REPOSITORY}/${DOCKER_IMAGE}:${{ env.TAG_NAME }}

  roc-tunnel:
    runs-on: ubuntu-latest
    env:
      DOCKER_REGISTRY: ghcr.io
      DOCKER_REPOSITORY: yusufcanb/roc
      DOCKER_IMAGE: roc-tunnel

    steps:
    - name: checkout
      uses: actions/checkout@v2

    - name: publish
      uses: docker/build-push-action@v2
      with:
        push: true
        context: .
        dockerfile: Dockerfile.tunnel
        tags: ${DOCKER_REGISTRY}/${DOCKER_REPOSITORY}/${DOCKER_IMAGE}:${{ env.TAG_NAME }}

    - name: Publish Docker Image
      uses: docker/push-action@v1
      with:
        tags: ${DOCKER_REGISTRY}/${DOCKER_REPOSITORY}/${DOCKER_IMAGE}:${{ env.TAG_NAME }}
