name: e2e

on: [push]

jobs:
  cli:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: python -m pip install -r requirements.txt
        working-directory: ./e2e

      - name: Deploy ROC
        run: docker-compose -f services.yaml up -d

      - name: Run E2E Tests
        run: python -m robot -v DEBUG:True tests/cli.robot
        working-directory: ./e2e

      - uses: actions/upload-artifact@v3
        with:
          name: e2e-output
          path: |
            ./e2e/output.xml
            ./e2e/report.html
            ./e2e/log.html

  platform:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: python -m pip install -r requirements.txt
        working-directory: ./e2e

      - name: Deploy ROC
        run: docker-compose -f services.yaml up -d

      - name: Run E2E Tests
        run: python -m robot -v DEBUG:True tests/platform.robot
        working-directory: ./e2e

      - uses: actions/upload-artifact@v3
        with:
          name: e2e-output
          path: |
            ./e2e/output.xml
            ./e2e/report.html
            ./e2e/log.html
